# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  pfrb:
    image: obyoxar/pathfinderre
    restart: always
    ports:
      - 3000:3000
